version: '3.1'

services:
    go-migrations:
        build: ../migrator
        container_name: go-migrate
        command: -path=/migrations/ -database postgres://postgres:postgres@localhost:5432/pods_management up
        network_mode: 'host'
        depends_on:
            - postgres_server

    postgres_server:
        image: postgres:12
        container_name: postgres-server
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_DB=postgres"
            - "POSTGRES_PASSWORD=pods_management"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        network_mode: 'host'

    redis_server:
        image: redis
        container_name: redis-server
        command: redis-server --requirepass redis_password
        volumes:
            - redis_data:/var/lib/redis/data
        ports:
            - 6379:6379
        network_mode: 'host'

volumes:
    postgres_data: {}
    redis_data: {}